[package]
name = "merfishtools"
version = "0.1.0"
authors = ["Johannes Koester <johannes.koester@tu-dortmund.de>"]

[dependencies]
bio = ">=0.3.16"
csv = "*"
nalgebra = "*"
itertools = "*"
rand = "*"
randomkit = "*"
num = "*"
rustc-serialize = "*"
argparse = "*"
log = "*"
fern = "*"
simple_parallel = "*"
crossbeam = "*"

[[bin]]
name = "merfishtools"
test = false
doc = false
