[package]
name = "merfishtools"
version = "1.0.0"
authors = ["Johannes Koester <johannes.koester@tu-dortmund.de>"]

[dependencies]
bio = "0.6.*"
regex = "0.1.41"
bit-set = "0.4.*"
csv = "0.14.3"
nalgebra = "0.5.1"
itertools = "0.4.7"
num = "0.1.31"
rustc-serialize = "0.3.16"
argparse = "0.2.1"
log = "0.3.5"
fern = "0.3.5"
cue = "0.1.*"
GSL = "0.4.25"
ord_subset = "1.2.0"
approx = "0.1.0"
fnv = "1.0.2"
clap = {version = "2.9.*", features = ["yaml", "color", "suggestions"]}
rand = "0.3"

[[bin]]
name = "merfishtools"
test = false
doc = false
