[package]
name = "merfishtools"
version = "0.1.0"
authors = ["Johannes Koester <johannes.koester@tu-dortmund.de>"]

[dependencies]
bio = { git = "https://github.com/rust-bio/rust-bio.git" }
regex = "0.1.41"
csv = "*"
nalgebra = "*"
itertools = "*"
rand = "*"
randomkit = "*"
num = "*"
rustc-serialize = "*"
argparse = "*"
log = "*"
fern = "*"
simple_parallel = "0.3"
crossbeam = "0.1"
GSL = "*"

[[bin]]
name = "merfishtools"
test = false
doc = false
