[package]
name = "merfishtools"
version = "0.1.0"
authors = ["Johannes Koester <johannes.koester@tu-dortmund.de>"]

[dependencies]
bio = "*"
csv = "*"
nalgebra = "*"
itertools = "*"
rand = "*"
GSL = "*"
randomkit = "*"
num = "*"
rustc-serialize = "*"
argparse = "*"
log = "*"
fern = "*"

[[bin]]
name = "merfishtools"
test = false
doc = false
