groups:
  A: "^[0-9]$"
  B: "^1[0-9]$"
  cell0: "^0$"
  cell34: "^34$"
  all: ".*"

datasets:
  140genesData:
    dist: 4
    N: 16
    experiments: 7
  1001genesData:
    dist: 2
    N: 14
    experiments: 3
  simulated-MHD4:
    dist: 4
    N: 16
    experiments: 1
  simulated-MHD2:
    dist: 2
    N: 14
    experiments: 1

codebooks:
  140genesData:
    1: codebook/140genesData.1.txt
    2: codebook/140genesData.2.txt
    3: codebook/140genesData.1.txt
    4: codebook/140genesData.2.txt
    5: codebook/140genesData.2.txt
    6: codebook/140genesData.1.txt
    7: codebook/140genesData.1.txt
  1001genesData:
    1: codebook/1001genesData.txt
    2: codebook/1001genesData.txt
    3: codebook/1001genesData.txt
  simulated-MHD4: codebook/simulated-MHD4.txt
  simulated-MHD2: codebook/simulated-MHD2.txt

settings:
  default:

genes:
  - COL5A1
  - BRCA2
  - CKAP5
  - ATP11A

plots:
  figsize: [4.224, 2.904]
