channels:
- bioconda
- ostrokach
dependencies:
- at-spi2-atk=2.16.0=1
- at-spi2-core=2.16.0=1
- atk=2.16.0=2
- bioconductor-annotate=1.48.0=1
- bioconductor-annotationdbi=1.32.2=0
- bioconductor-annotationforge=1.12.2=0
- bioconductor-biobase=2.30.0=0
- bioconductor-biocgenerics=0.16.1=r3.2.2_0
- bioconductor-biomart=2.26.1=r3.2.2_0
- bioconductor-category=2.36.0=r3.2.2_0
- bioconductor-genefilter=1.52.0=r3.2.2_0
- bioconductor-go.db=3.2.2=0
- bioconductor-gostats=2.36.0=0
- bioconductor-graph=1.48.0=1
- bioconductor-gseabase=1.32.0=0
- bioconductor-iranges=2.4.6=0
- bioconductor-multtest=2.26.0=0
- bioconductor-org.hs.eg.db=3.2.3=0
- bioconductor-rbgl=1.46.0=r3.2.2_0
- bioconductor-rgraphviz=2.14.0=0
- bioconductor-s4vectors=0.8.7=0
- bison=3.0.4=2
- bitarray=0.8.1=py35_0
- cairo=1.12.18=6
- curl=7.45.0=1
- cycler=0.9.0=py35_0
- dbus=1.8.20=1
- dbus-glib=0.104=1
- docutils=0.12=py35_0
- expat=2.1.0=0
- flex=2.5.39=2
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- gdk-pixbuf=2.30.8=3
- gettext=0.19.5=2
- glib=2.44.1=2
- gobject-introspection=1.44.0=3
- gsl=1.16=1
- gtk=3.16.6=2
- harfbuzz=1.0.1=2
- icu=55.1=0
- jbig=2.1=0
- jpeg=8d=0
- libcroco=0.6.8=1
- libepoxy=1.3.1=1
- libffi=3.2.1=7
- libgcc=4.8.5=1
- libgfortran=3.0=0
- libgsf=1.14.34=1
- libpng=1.6.17=0
- librsvg=2.40.10=3
- libsigcpp=2.4.1=1
- libtiff=4.0.6=1
- libxml2=2.9.3=0
- libxslt=1.1.28=0
- lxml=3.6.0=py35_0
- matplotlib=1.5.1=np110py35_0
- mkl=11.3.1=0
- ncurses=5.9=4
- nomkl=1.0=0
- numpy=1.10.4=py35_nomkl_1
- openblas=0.2.14=4
- openssl=1.0.2e=0
- pandas=0.17.1=np110py35_0
- pango=1.39.0=0
- patsy=0.4.0=np110py35_0
- pcre=8.31=0
- pip=8.0.1=py35_0
- pixman=0.32.6=4
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- qt=4.8.7=1
- r=3.2.2=0
- r-base=3.2.2=0
- r-bitops=1.0_6=r3.2.2_1a
- r-boot=1.3_17=r3.2.2_0a
- r-class=7.3_14=r3.2.2_0a
- r-cluster=2.0.3=r3.2.2_0a
- r-codetools=0.2_14=r3.2.2_0a
- r-dbi=0.3.1=r3.2.2_2a
- r-foreign=0.8_66=r3.2.2_0a
- r-kernsmooth=2.23_15=r3.2.2_0a
- r-lattice=0.20_33=r3.2.2_0a
- r-mass=7.3_45=r3.2.2_0a
- r-matrix=1.2_2=r3.2.2_0a
- r-mgcv=1.8_9=r3.2.2_0a
- r-multcomp=1.4_1=r3.2.2_0a
- r-mutoss=0.1_10=r3.2.2_0
- r-mvtnorm=1.0_3=r3.2.2_0a
- r-nlme=3.1_122=r3.2.2_0a
- r-nnet=7.3_11=r3.2.2_0a
- r-plotrix=3.6_1=r3.2.2_0
- r-rcurl=1.95_4.7=r3.2.2_0a
- r-recommended=3.2.2=r3.2.2_0
- r-rpart=4.1_10=r3.2.2_0a
- r-rsqlite=1.0.0=r3.2.2_1a
- r-sandwich=2.3_4=r3.2.2_0a
- r-spatial=7.3_11=r3.2.2_0a
- r-survival=2.38_3=r3.2.2_0a
- r-th.data=1.0_6=r3.2.2_1a
- r-xml=3.98_1.3=r3.2.2_0a
- r-xtable=1.8_0=r3.2.2_0a
- r-zoo=1.7_12=r3.2.2_1a
- readline=6.2=2
- rpy2=2.7.6=py35r3.2.2_0
- rust=1.6.0=0
- scikit-learn=0.17.1=np110py35_nomkl_0
- scipy=0.17.0=np110py35_nomkl_2
- seaborn=0.7.0=py35_0
- setuptools=19.4=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- snakemake=3.6.1=py35_0
- sqlite=3.9.2=0
- statsmodels=0.6.1=np110py35_0
- svgutils=0.1.0=py35_0
- system=5.8=2
- tk=8.5.18=0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0

